INSERT INTO RANK VALUES ('bob',1);

INSERT INTO RANK VALUES ('미국',2);

INSERT INTO RANK VALUES ('한국',3);

INSERT INTO RANK VALUES ('test',4);

INSERT INTO RANK VALUES ('tt',5);

INSERT INTO RANK VALUES ('tes',6);

INSERT INTO RANK VALUES ('ts',7);

INSERT INTO RANK VALUES ('tst',8);

INSERT INTO RANK VALUES ('st',9);

INSERT INTO RANK VALUES ('est',10);

INSERT INTO RANK VALUES ('tet',11);