INSERT INTO RANK VALUES ('Korea',9);

INSERT INTO RANK VALUES ('Kakao',8);

INSERT INTO RANK VALUES ('Bank',7);

INSERT INTO RANK VALUES ('Bts',6);

INSERT INTO RANK VALUES ('chanyeong',5);

INSERT INTO RANK VALUES ('Together',4);

INSERT INTO RANK VALUES ('Communication',3);